const family = [
  {
    id: 1,
    fName: "Sardor",
    lName: "Vohobov",
    tell: "tel:+998999999999",
    instagram: "https://www.instagram.com/?url=https://www.drdrop.co/",
    telegram: "https://telegram.me/umida",
    address: "Tashkent shahar Olmazor tumani Beruniy mahallasi 7-uy",
    image: "https://www.wrraptheme.com/templates/alpino/main/assets/images/sm/avatar1.jpg",
  },
  {
    id: 2,
    fName: "Umida",
    lName: "Vohobova",
    tell: "tel:+998999999999",
    instagram: "https://www.instagram.com/?url=https://www.drdrop.co/",
    telegram: "https://telegram.me/umida",
    address: "Tashkent shahar Olmazor tumani Beruniy mahallasi 7-uy",
    image: "https://www.wrraptheme.com/templates/alpino/main/assets/images/sm/avatar3.jpg",
  },
  {
    id: 3,
    fName: "Anvar",
    lName: "Vohobov",
    tell: "tel:+998999999999",
    instagram: "https://www.instagram.com/?url=https://www.drdrop.co/",
    telegram: "https://telegram.me/umida",
    address: "Tashkent shahar Olmazor tumani Beruniy mahallasi 7-uy",
    image: "https://www.wrraptheme.com/templates/alpino/main/assets/images/sm/avatar2.jpg",
  },
  {
    id: 4,
    fName: "Dovron",
    lName: "Vohobov",
    tell: "tel:+998999999999",
    instagram: "https://www.instagram.com/?url=https://www.drdrop.co/",
    telegram: "https://telegram.me/umida",
    address: "Tashkent shahar Olmazor tumani Beruniy mahallasi 7-uy",
    image: "https://www.wrraptheme.com/templates/alpino/main/assets/images/sm/avatar5.jpg",
  },
  {
    id: 5,
    fName: "Malika",
    lName: "Vohobova",
    tell: "tel:+998999999999",
    instagram: "https://www.instagram.com/?url=https://www.drdrop.co/",
    telegram: "https://telegram.me/umida",
    address: "Tashkent shahar Olmazor tumani Beruniy mahallasi 7-uy",
    image: "https://www.wrraptheme.com/templates/alpino/main/assets/images/sm/avatar4.jpg",
  },
];

const work = [
  {
    id: 1,
    name: "Napa",
    position: "coder",
    entered: "07.07.2000",
    finished: "10.10.2005",
  },
  {
    id: 2,
    name: "Smart SoftWare",
    position: "coder",
    entered: "07.07.2005",
    finished: "10.10.2010",
  },
  {
    id: 3,
    name: "TATU",
    position: "coder",
    entered: "07.07.2010",
    finished: "10.10.2015",
  },
  {
    id: 4,
    name: "Turin",
    position: "coder",
    entered: "07.07.2015",
    finished: "10.10.2017",
  },
  {
    id: 5,
    name: "EPAM",
    position: "coder",
    entered: "07.07.2017",
    finished: "10.10.2019",
  },
  {
    id: 6,
    name: "Click",
    position: "coder",
    entered: "07.07.2020",
    finished: "10.10.2020",
  },
  {
    id: 7,
    name: "Payme",
    position: "coder",
    entered: "07.07.2020",
    finished: "10.10.2021",
  },
  {
    id: 8,
    name: "Google",
    position: "coder",
    entered: "07.07.2021",
    finished: "hozirgacha",
  },
];

const komunal = [
  { id: 1, name: "elektr energiya", paid: "1000$", debt: "0$" },
  { id: 2, name: "gaz", paid: "1000$", debt: "0$" },
  { id: 3, name: "sovuq suv", paid: "1000$", debt: "0$" },
  { id: 4, name: "issiq suv", paid: "1000$", debt: "0$" },
  { id: 6, name: "musur", paid: "1000$", debt: "0$" },
  { id: 5, name: "yer solig'i", paid: "1000$", debt: "0$" },
  { id: 7, name: "uy-joy solig'i", paid: "1000$", debt: "0$" },
];
const schools = [
  {
    id: 1,
    name: "255-maktam",
    address: "Tashkent Olmazor tumani",
    entered: "07.07.1990",
    finished: "07.07.1994",
  },
  {
    id: 2,
    name: "152-maktam",
    address: "Tashkent Olmazor tumani",
    entered: "07.07.1994",
    finished: "07.07.1999",
  },
  {
    id: 3,
    name: "TAKXK",
    address: "Tashkent Shayhotohur tumani",
    entered: "07.07.1999",
    finished: "07.07.2002",
  },
  {
    id: 4,
    name: "Najot Ta'lim",
    address: "Tashkent Olmazor tumani",
    entered: "07.07.2002",
    finished: "07.07.2003",
  },
  {
    id: 5,
    name: "TATU",
    address: "Tashkent Yunosobod tumani",
    entered: "07.07.2003",
    finished: "07.07.2007",
  },
  {
    id: 6,
    name: "PDP",
    address: "Tashkent Shayhotohur tumani",
    entered: "07.07.2007",
    finished: "07.07.2008",
  },
  {
    id: 7,
    name: "TDTU",
    address: "Tashkent Olmazor tumani",
    entered: "07.07.2008",
    finished: "07.07.2012",
  },
  {
    id: 8,
    name: "Harvard",
    address: "USA",
    entered: "07.07.2012",
    finished: "07.07.2015",
  },
];

module.exports = {
  family,
  work,
  komunal,
  schools,
};
